---
# Download JAVA from Oracle

- name: download Java RPM
  get_url:
    headers: 'Cookie:gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie' 
    dest: "{{ java_install_dir }}/{{ java_src_tar }}"
    url: "{{ java_download_url }}"
    validate_certs: yes
    timeout: 10
  register: oracle_java_task_tar_download
  until: oracle_java_task_tar_download|succeeded 
  become: yes

