---
- name: determine if Java is already installed
  shell: which java
  register: task_installed_java
  changed_when: task_installed_java.rc != 0
  failed_when: no

- name: set fact installed_java
  set_fact:
    installed_java={{ not task_installed_java.changed }}

- name: determine which Java version is installed
  shell: java -version
  when: installed_java
  register: task_installed_java_version
  changed_when: False

- name: set fact installed_java_version
  set_fact:
    java_version_installed="{{ task_installed_java_version.stderr.split('\n')[0]|regex_replace('.*\"(.*)\"','\\1') }}"
  when: task_installed_java_version is defined and task_installed_java_version.stdout is defined
  changed_when: False

- debug:
    var="{{ item }}"
  when: item is defined and debug | default(false)
  with_items:
    - installed_java
    - task_installed_java
    - task_installed_java_version
    - java_version_installed
    - java_version_string

- name: set internal vars for 1.8.0_172
  set_fact:
    java_download_url: "http://download.oracle.com/otn-pub/java/jdk/{{java_main_rel}}u{{java_min_rel}}-b11/{{jdk172_b11}}/jdk-{{java_main_rel}}u{{java_min_rel}}-linux-x64.tar.gz"
  when: java_main_rel == 8 and java_min_rel == 172

- name: set internal vars for 1.8.0_171
  set_fact:
    java_download_url: "http://download.oracle.com/otn-pub/java/jdk/{{ java_main_rel }}u{{ java_min_rel }}-b11/{{jdk171_b11}}/jdk-{{java_main_rel}}u{{java_min_rel}}-linux-x64.tar.gz"
  when: java_main_rel == 8 and java_min_rel == 171

# - name: Show Download url
#   debug:
#     msg: "{{java_download_url}}"

- name: Check if File Exists
  stat:
    path: "{{java_data_dir}}/{{java_src_tar}}"
  register: jdk_already_present


- name: download Java RPM
  get_url:
    headers: 'Cookie:gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie'
    dest: "{{ java_data_dir }}/{{java_src_tar}}"
    url: "{{ java_download_url }}"
    validate_certs: yes
  register: oracle_java_task_tar_download
  until: oracle_java_task_tar_download is succeeded
  retries: 10
  delay: 5
  when: jdk_already_present.stat.exists == False 